### ISSUE TITLE
google oauth fails

### ISSUE THREAD

**Issue by timtim17** [JVenberg/UWSchedule2GoogleCalendar#1]
Hey Jack! I was browsing through GitHub the other day and happend to find your extension, which seemed like something that could actually be really useful for me! However, signing into Google Calendar didn't seem to work. After a bit of debugging with devtools, it seems like the app no longer exists on the Google Dev Console side of things. It reports the client was deleted, so I was curious if that was for a reason. I get if this is just like a side project or unmaintained or something, just curious :D

![image](https://user-images.githubusercontent.com/6354860/62042895-03f30a80-b1b4-11e9-83bc-bc3cc241fd2f.png)
![image](https://user-images.githubusercontent.com/6354860/62042956-2127d900-b1b4-11e9-9ee1-5ab53560e0e3.png)
Value of `auth.url`
```
https://accounts.google.com/o/oauth2/auth?client_id=27717438855-h3dr1msj1158ett67g99jgp2bpans90i.apps.googleusercontent.com&response_type=id_token%20token&prompt=select_account&redirect_uri=https%3A%2F%2Feijbpemmnficdlgkngbfoelfpbjolaia.chromiumapp.org%2F&scope=openid%20email%20profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar
```
![image](https://user-images.githubusercontent.com/6354860/62043006-41579800-b1b4-11e9-97f3-828a850fc7ac.png)

**Comment by JVenberg** [comment]
Thanks for the heads up! I pushed an update a few weeks ago fixing this. Apparently the API changed and required another parameter too.
